import StringForm from "./StringForm";
import NumberForm from "./NumberForm";
import SelectForm from "./SelectForm";
import DateForm from "./DateForm";
import TimeForm from "./TimeForm";
import TimeRangeForm from "./TimeRangeForm";
import DateRangeForm from "./DateRangeForm";
import CascaderForm from "./CascaderForm";
import RemoteSearchForm from "./RemoteSearchForm";
export declare const FormItemComponents: {
    StringForm: typeof StringForm;
    NumberForm: typeof NumberForm;
    SelectForm: typeof SelectForm;
    DateForm: typeof DateForm;
    TimeForm: typeof TimeForm;
    TimeRangeForm: typeof TimeRangeForm;
    DateRangeForm: typeof DateRangeForm;
    CascaderForm: typeof CascaderForm;
    RemoteSearchForm: typeof RemoteSearchForm;
};
